### ISSUE TITLE
I can't use learner command when I type I will get an error 😢😭

### ISSUE THREAD

**Issue by shreesha345** [GandyT/Learner#3]
`node-pre-gyp info This Node instance does not support builds for Node-API version 8
node-pre-gyp info This Node instance does not support builds for Node-API version 8
2021-06-23 11:38:20.803379: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Bot is now on!
(node:6604) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/content/Learner/node_modules/node-fetch/lib/index.js:1305:9)
    at /content/Learner/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/content/Learner/node_modules/node-fetch/lib/index.js:1407:9)
    at HTTPRequest.PlatformNode.fetch (/content/Learner/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:7330:16)
    at HTTPRequest.<anonymous> (/content/Learner/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8280:55)
    at step (/content/Learner/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:82:23)
    at Object.next (/content/Learner/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:63:53)
    at /content/Learner/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:56:71
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
I am getting this error please help me to fix it 😭😭😭😭

**Comment by shreesha345** [comment]
please some one help

**Comment by randall-sim** [comment]
Could it be that you are using an older version of node.js? Try updating your node.js to the latest stable version

**Comment by shreesha345** [comment]
I am doing it in google colab notebook

**Comment by randall-sim** [comment]
Try to see if you can change the version of node.js on whichever site you are using. It seems like it's a node.js version problem.

**Comment by shreesha345** [comment]
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated discord.js@11.6.4: no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is kPS D:\Cleve> npm install @tensorflow/tfjs-node

> @tensorflow/tfjs-node@3.7.0 install D:\Cleve\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

CPU-windows-3.7.0.zip
* Downloading libtensorflow
[==============================] 177095/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install request to https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/3.7.0/CPU-windows-3.7.0.zip failed, reason: getaddrinfo ENOTFOUND storage.googleapis.com
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@3.7.0 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error request to https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/3.7.0/CPU-windows-3.7.0.zip failed, reason: getaddrinfo ENOTFOUND storage.googleapis.com
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.10.31410.357) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS checking VS2017 (15.9.28307.1525) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)  
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Cleve\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v7\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=D:\\Cleve\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v7" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=7" "--node_napi_label=napi-v7"
gyp ERR! cwd D:\Cleve\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\nodejs\node.exe D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\Cleve\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node --module_name=tfjs_binding --module_path=D:\Cleve\node_modules\@tensorflow\tfjs-node\lib\napi-v7 --napi_version=7 --node_abi_napi=napi --napi_build_version=7 --node_napi_label=napi-v7' (1)   
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Cleve\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "D:\\nodejs\\node.exe" "D:\\Cleve\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Cleve\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.4
node-pre-gyp ERR! not ok

npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@3.7.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tensorflow/tfjs-node@3.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2021-06-28T05_33_47_225Z-debug.log`
when I install the @tensorflow/tfjs-node the error comes.

**Comment by shreesha345** [comment]
when I try to install in locally in my computer this error comes👆 , but I have installed C++ build tools but also it comes the same thing..

**Comment by wanderdevof** [comment]
I resolved with this:

[](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)

**Comment by wanderdevof** [comment]
I resolved with this:

https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools
